ci: added doc8 linting for docs

diff --git a/.gitlab/ci/.gitlab-ci-check.yml b/.gitlab/ci/.gitlab-ci-check.yml
--- a/.gitlab/ci/.gitlab-ci-check.yml
+++ b/.gitlab/ci/.gitlab-ci-check.yml
@@ -26,6 +26,12 @@ check_codebase:
         echo "Djlint failed, please check "$CHECK_REPORT_PATH"djlint_prebuild.ansi ."
         exit 1
       fi
+    - poetry run doc8 --config $CHECK_CONFIG_PATH'doc8.ini' docs/ >> $CHECK_REPORT_PATH'doc8_prebuild.ansi'
+    - |
+      if [ $? -ne 0 ]; then
+        echo "Doc8 failed, please check "$CHECK_REPORT_PATH"doc8_prebuild.ansi ."
+        exit 1
+      fi
     - poetry run codespell --config=$CHECK_CONFIG_PATH'.codespellrc' Emailkasten/ core/ api/ web/ test/ docs/ .gitea/ .github/ .gitlab/ *.md >> $CHECK_REPORT_PATH'codespell_prebuild.ansi'
     - echo "Successfully checked codebase."
   artifacts:
diff --git a/validation/githooks/pre-commit b/validation/githooks/pre-commit
--- a/validation/githooks/pre-commit
+++ b/validation/githooks/pre-commit
@@ -54,6 +54,18 @@ else
   fi
 fi
 
+CHANGED_RST_FILES=$(git diff --cached --name-only --diff-filter=ACMRT | grep '\.rst$')
+
+if [ -z "$CHANGED_RST_FILES" ]; then
+  echo "No html files in commit."
+else
+  poetry run doc8 --config $CONFIG_PATH'doc8.ini' $CHANGED_RST_FILES >> $REPORT_PATH'doc8_precommit.ansi'
+  if [ $? -ne 0 ]; then
+    echo "Doc8 failed, please check "$REPORT_PATH"doc8_precommit.ansi ."
+    exit 1
+  fi
+fi
+
 #spellcheck
 poetry run codespell --config=$CONFIG_PATH'.codespellrc' Emailkasten/ core/ api/ web/ test/ docs/ .gitea/ .github/ .gitlab/ *.md >> $REPORT_PATH'codespell_precommit.ansi'
 
